name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6', '1.9', 'nightly']
        os: [ubuntu-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'
      - run: julia --project=@. -e 'using Pkg; Pkg.test()'

  docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
      - run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          keep_files: true

  benchmark:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
      - run: julia --project=@. -e 'using Pkg; Pkg.add("BenchmarkTools")'
      - run: julia --project=@. benchmark/run.jl